### ISSUE TITLE
External resourceを作成したタイミングでキャッシュが破棄されていない

### ISSUE THREAD

**Issue by lestrrat** [builderscon/admin.builderscon.io#39]
![image](https://cloud.githubusercontent.com/assets/49281/21663798/c94f9ff2-d325-11e6-8d4a-907b84614d37.png)

この後「Togetter」というリソースを作ったけど、リロードしても反映されない :/

**Comment by richardimaoka** [comment]
From Slack
>lestrrat [9:04 AM 2017/01/05]  
>@richard マージ＋デプロイしたけど、キャッシュの破棄がうまくいってないみたい。
>[9:05]  
>とりあえず手動で破棄しとこう
>[9:07]  
>キャッシュから”octav.ExternalResource.LoadByConferenceID.fdd2e7aa-b234-4aac-bfb1-e58cb334e8a7.2016-11-17”を手動破棄したら期待していた通りの表示が出たので、やっぱりキャッシュ破棄がうまくできてない模様。

**Comment by richardimaoka** [comment]
memo for myself

[GCP log with filter = doCreateExternalResource](https://console.cloud.google.com/logs/viewer?project=builderscon-1248&minLogLevel=0&expandAll=true&resource=container%2Fcluster_name%2Fbuilderscon-prd2&pli=1&filters=text:doCreateExternalResource&timestamp=2017-01-05T00:02:20.000000000Z)

[log @09:02:20 on 2017/1/5](https://console.cloud.google.com/logs/viewer?project=builderscon-1248&minLogLevel=0&expandAll=false&resource=container%2Fcluster_name%2Fbuilderscon-prd2&pli=1&timestamp=2017-01-05T00:02:19.000000000Z)

//the request for togetter creation
>09:02:20.000
|DEBUG| 1483574540599.35474 END doCreateExternalResource (22.362892ms)

**Comment by richardimaoka** [comment]
ローカルで再現を試みるも再現できず、本番環境のログを見ても原因が判明しなかったので、

本番環境のmooconfで再現を試みます。

### 以下ここまでの調査内容
lestrratさんがイシューを見つけたのはこの時点
```
lestrrat [2017/01/05 9:04 AM] @richard マージ＋デプロイしたけど、キャッシュの破棄がうまくいってないみたい。
[9:05]  とりあえず手動で破棄しとこう
[9:07]  キャッシュから”octav.ExternalResource.LoadByConferenceID.fdd2e7aa-b234-4aac-bfb1-e58cb334e8a7.2016-11-17”
を手動破棄したら期待していた通りの表示が出たので、
やっぱりキャッシュ破棄がうまくできてない模様。
```

Togetterのリソースが追加されたのはその2分前
>09:02:20.000|DEBUG| 1483574540576.98486 START doCreateExternalResource

で、なんとキャッシュが正しく消されていた模様...
>09:02:20.000|DEBUG| 1483574540592.23901 CACHE DEL: octav.ExternalResource.LoadByConferenceID.fdd2e7aa-b234-4aac-bfb1-e58cb334e8a7.2016-11-17

そして、Togetterを追加した直後のlookupでは
>09:02:20.000|DEBUG| 1483574540786.29712 START httpLookupConference

octavはちゃんとTogetterのリソースを含んだJSONを返している
>09:02:21.000|DEBUG| 1483574541028.87207 response buffer: {"id":"fdd2e7aa-b234-4aac-bfb1-e58cb334e8a7","title":"builderscon tokyo 2016", …

```
   "external_resources":[  
      {  
         "id":"4d19479a-288a-4040-bd6d-dc6f03cdc8f8",
         "conference_id":"fdd2e7aa-b234-4aac-bfb1-e58cb334e8a7",
         "description":"Official photo set for the conference is available! Have a look, and feel free to use them (CC-BY-NC 4.0 license)!",
         "title":"Photos",
         "url":"https://goo.gl/photos/svZFdZWWzNNHP8tb7",
         "sort_order":0,
         "description#ja":"カンファレンスの公式写真です！お気軽にご利用ください (CC-BY-NC 4.0ライセンス)",
         "title#ja":"写真"
      },
      {  
         "id":"41fa07d2-77ef-4aa8-b9e4-049814a062ca",
         "conference_id":"fdd2e7aa-b234-4aac-bfb1-e58cb334e8a7",
         "description":"Videos from the sessions are available for your viewing pleasure!",
         "title":"Videos",
         "url":"https://www.youtube.com/c/builderscon",
         "sort_order":0,
         "description#ja":"カンファレンスセッションの動画、絶賛公開中です。スライドは各セッションのページよりご覧下さい。",
         "title#ja":"動画"
      },
      {  
         "id":"9526e477-0abd-4cca-9c51-71a6c203fa53",
         "conference_id":"fdd2e7aa-b234-4aac-bfb1-e58cb334e8a7",
         "description":"Tweets about the conference",
         "title":"Togetter",
         "url":"https://togetter.com/li/1055469",
         "sort_order":0,
         "description#ja":"カンファレンスに関するツイートのまとめ",
         "title#ja":"Togetter"
      }
   ],
```

>09:02:21.000|DEBUG| 1483574541032.01172 END (244.138106ms)

この直後のLookupConferenceは9時6分なので、

>09:06:19.000|DEBUG| 1483574779564.51074 START doLookupConferenceBySlug

>09:06:37.000|DEBUG| 1483574797407.62598 START doLookupConference

すでにlestrratさんがキャッシュをクリアした後。
つまり、lestrratさんが「Togetter」見えないと言ったときのoctavからの応答は、上記のTogetterを含む`09:02:21.000|DEBUG| 1483574541028.87207`のように思えるのだが…だとしたらTogetterが見えなかった理由が説明できない。

もしconf側でキャッシュされたことが原因で見えなかったのだとしたら、octav側のキャッシュであるこれを消去したらTogetterが見えたことが説明できない。

>octav.ExternalResource.LoadByConferenceID.fdd2e7aa-b234-4aac-bfb1-e58cb334e8a7.2016-11-17

**Comment by lestrrat** [comment]
なるほど、conf側のキャッシュか。それはその時考えつかなかったけど、もっともな理由かも。

**Comment by richardimaoka** [comment]
は、早い...! ww

コメントありがとうございます。
conf側のキャッシュだとすると、ローカルで再現できなかったのとlestrratさんがoctavのキャッシュをクリアした時点で見えるようになったのが説明できないかな？と思うのでmooconfで試したいです。

SlackでDMしましたが、admin本番のパスワードもう一度教えていただけますと助かります...

**Comment by lestrrat** [comment]
まぁ、微妙なところですね。とらいえずぱっとわからなかったら、あとまわしでもいいです。
あ、今Slackが起動してない…

**Comment by richardimaoka** [comment]
conf側でのキャッシュが原因だと思われます。

300秒経てばconfのキャッシュが期限切れになるので、何もせずこのイシューはcloseで良いでしょうか？

### 追加調査のまとめ

conf.builderscon.ioの[hooks.py](https://github.com/builderscon/conf.builderscon.io/blob/1f9244b26d6895e7511468425a5efe70ecc53da2/app/hooks.py#L6)にこれがあります
> CACHE_CONFERENCE_EXPIRES = 300

lestrratさんがoctavのキャッシュをクリアした後conf側でTogetterが見えたのは、
おそらくはたまたま300秒経ったからではないかと推測します。

私のローカル環境でも、この現象は再現できました。
以前再現できなかったのは、私がブレークポイントを置いてデバッグしていたため、conf側での描画に300秒以上の時間がかかっていたと思われます。

**Comment by lestrrat** [comment]
おすー。ありがとうございました！
