### ISSUE TITLE
modify sponsor feature

### ISSUE THREAD

**Issue by morizooo** [builderscon/admin.builderscon.io#47]
- 削除機能を追加する

- スポンサー追加時成功時にわからない&F5押さないと更新されないので修正する

- 更新時にロゴURLが変わらないので修正する

**Comment by lestrrat** [comment]
削除機能とF5更新は直した。

**Comment by lestrrat** [comment]
@morizooo この「更新時にロゴURLが変わらないので修正する」って具体的にどういう状態です？

**Comment by morizooo** [comment]
英語版と日本語版わかれているの気づかなくて、英語版だけURL変更していて日本語環境で見たときの勘違いでした！

**Comment by lestrrat** [comment]
なるほど。じゃあ一旦できたと思うのでクローズしておきますー
